---
title: RebeccaCox_A01_Introduction.Rmd
author: Becca Cox
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I used R/RStudio a tiny bit during my senior year of college (two years ago), but a lot of the code was fed to us so I don't feel like I can code/navigate RStudio on my own.

2. Are there any components of the course about which you feel confident?

> Answer: I feel like I have a good grasp of what data is, how it can be organized, and the basics of what we're doing/looking at when we analyze it.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I don't know how to code! I am a total beginner so am apprehensive about figuring it all out.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/beccaeco/EDE_Fall2024

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
